# Generated by Django 5.1.4 on 2024-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0004_alter_customuser_email_alter_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='STUDENT', help_text='Specifies the role of the user.', max_length=50, verbose_name='Role'),
        ),
    ]
