# Generated by Django 5.1.4 on 2025-02-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
