# Generated by Django 5.1.4 on 2025-03-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
