# Generated by Django 5.1.4 on 2025-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='module_contents/'),
        ),
    ]
